version: "3.8"


services:

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  test:
    image: python:3.7
    volumes:
      - ./test:/test
    command: sleep infinity
    depends_on:
      - redis
